### ISSUE TITLE
[iOS] Document how to embed Experience View Controller within a UIKit view controller.

### ISSUE THREAD

**Issue by orospakr** [judoapp/judo-developer-site#11]
Put a new page called "Embedding" within the Customization section.

Explain limitations, namely that we cannot do autosizing from content and that the nested ExperienceViewController will need to be given a fixed size.

**Comment by Moux** [comment]
Completed with 4e848f991cf759cb7ca33bc44c800be069595fb0.  Please close this ticket when review is complete.

**Comment by orospakr** [comment]
review +1
